sudo: required
services:
  - docker

before_install:
  - docker build -t margitacorp/fe-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true margitacorp/fe-react-app npm run test -- --coverage
